// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/championship.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Championship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Championship) Reset() {
	*x = Championship{}
	mi := &file_proto_championship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Championship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Championship) ProtoMessage() {}

func (x *Championship) ProtoReflect() protoreflect.Message {
	mi := &file_proto_championship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Championship.ProtoReflect.Descriptor instead.
func (*Championship) Descriptor() ([]byte, []int) {
	return file_proto_championship_proto_rawDescGZIP(), []int{0}
}

func (x *Championship) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Championship) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Championship) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *Championship) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

type CreateChampionshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChampionshipRequest) Reset() {
	*x = CreateChampionshipRequest{}
	mi := &file_proto_championship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChampionshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChampionshipRequest) ProtoMessage() {}

func (x *CreateChampionshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_championship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChampionshipRequest.ProtoReflect.Descriptor instead.
func (*CreateChampionshipRequest) Descriptor() ([]byte, []int) {
	return file_proto_championship_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChampionshipRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChampionshipRequest) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *CreateChampionshipRequest) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

type ChampionshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Championship  *Championship          `protobuf:"bytes,1,opt,name=championship,proto3" json:"championship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChampionshipResponse) Reset() {
	*x = ChampionshipResponse{}
	mi := &file_proto_championship_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChampionshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChampionshipResponse) ProtoMessage() {}

func (x *ChampionshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_championship_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChampionshipResponse.ProtoReflect.Descriptor instead.
func (*ChampionshipResponse) Descriptor() ([]byte, []int) {
	return file_proto_championship_proto_rawDescGZIP(), []int{2}
}

func (x *ChampionshipResponse) GetChampionship() *Championship {
	if x != nil {
		return x.Championship
	}
	return nil
}

type ListChampionshipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChampionshipsRequest) Reset() {
	*x = ListChampionshipsRequest{}
	mi := &file_proto_championship_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChampionshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChampionshipsRequest) ProtoMessage() {}

func (x *ListChampionshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_championship_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChampionshipsRequest.ProtoReflect.Descriptor instead.
func (*ListChampionshipsRequest) Descriptor() ([]byte, []int) {
	return file_proto_championship_proto_rawDescGZIP(), []int{3}
}

type ListChampionshipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Championships []*Championship        `protobuf:"bytes,1,rep,name=championships,proto3" json:"championships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChampionshipsResponse) Reset() {
	*x = ListChampionshipsResponse{}
	mi := &file_proto_championship_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChampionshipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChampionshipsResponse) ProtoMessage() {}

func (x *ListChampionshipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_championship_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChampionshipsResponse.ProtoReflect.Descriptor instead.
func (*ListChampionshipsResponse) Descriptor() ([]byte, []int) {
	return file_proto_championship_proto_rawDescGZIP(), []int{4}
}

func (x *ListChampionshipsResponse) GetChampionships() []*Championship {
	if x != nil {
		return x.Championships
	}
	return nil
}

type UpdateChampionshipEndDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewEndAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=new_end_at,json=newEndAt,proto3" json:"new_end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChampionshipEndDateRequest) Reset() {
	*x = UpdateChampionshipEndDateRequest{}
	mi := &file_proto_championship_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChampionshipEndDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChampionshipEndDateRequest) ProtoMessage() {}

func (x *UpdateChampionshipEndDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_championship_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChampionshipEndDateRequest.ProtoReflect.Descriptor instead.
func (*UpdateChampionshipEndDateRequest) Descriptor() ([]byte, []int) {
	return file_proto_championship_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateChampionshipEndDateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateChampionshipEndDateRequest) GetNewEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NewEndAt
	}
	return nil
}

type DeleteChampionshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChampionshipRequest) Reset() {
	*x = DeleteChampionshipRequest{}
	mi := &file_proto_championship_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChampionshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChampionshipRequest) ProtoMessage() {}

func (x *DeleteChampionshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_championship_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChampionshipRequest.ProtoReflect.Descriptor instead.
func (*DeleteChampionshipRequest) Descriptor() ([]byte, []int) {
	return file_proto_championship_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteChampionshipRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteChampionshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChampionshipResponse) Reset() {
	*x = DeleteChampionshipResponse{}
	mi := &file_proto_championship_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChampionshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChampionshipResponse) ProtoMessage() {}

func (x *DeleteChampionshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_championship_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChampionshipResponse.ProtoReflect.Descriptor instead.
func (*DeleteChampionshipResponse) Descriptor() ([]byte, []int) {
	return file_proto_championship_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteChampionshipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_championship_proto protoreflect.FileDescriptor

const file_proto_championship_proto_rawDesc = "" +
	"\n" +
	"\x18proto/championship.proto\x12\x04game\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n" +
	"\fChampionship\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\bstart_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\"\x99\x01\n" +
	"\x19CreateChampionshipRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\bstart_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\"N\n" +
	"\x14ChampionshipResponse\x126\n" +
	"\fchampionship\x18\x01 \x01(\v2\x12.game.ChampionshipR\fchampionship\"\x1a\n" +
	"\x18ListChampionshipsRequest\"U\n" +
	"\x19ListChampionshipsResponse\x128\n" +
	"\rchampionships\x18\x01 \x03(\v2\x12.game.ChampionshipR\rchampionships\"l\n" +
	" UpdateChampionshipEndDateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\n" +
	"new_end_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bnewEndAt\"+\n" +
	"\x19DeleteChampionshipRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x1aDeleteChampionshipResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf8\x02\n" +
	"\x13ChampionshipService\x12Q\n" +
	"\x12CreateChampionship\x12\x1f.game.CreateChampionshipRequest\x1a\x1a.game.ChampionshipResponse\x12T\n" +
	"\x11ListChampionships\x12\x1e.game.ListChampionshipsRequest\x1a\x1f.game.ListChampionshipsResponse\x12_\n" +
	"\x19UpdateChampionshipEndDate\x12&.game.UpdateChampionshipEndDateRequest\x1a\x1a.game.ChampionshipResponse\x12W\n" +
	"\x12DeleteChampionship\x12\x1f.game.DeleteChampionshipRequest\x1a .game.DeleteChampionshipResponseB@Z>github.com/PatrickCalorioCarvalho/StrideClash/backend/proto;pbb\x06proto3"

var (
	file_proto_championship_proto_rawDescOnce sync.Once
	file_proto_championship_proto_rawDescData []byte
)

func file_proto_championship_proto_rawDescGZIP() []byte {
	file_proto_championship_proto_rawDescOnce.Do(func() {
		file_proto_championship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_championship_proto_rawDesc), len(file_proto_championship_proto_rawDesc)))
	})
	return file_proto_championship_proto_rawDescData
}

var file_proto_championship_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_championship_proto_goTypes = []any{
	(*Championship)(nil),                     // 0: game.Championship
	(*CreateChampionshipRequest)(nil),        // 1: game.CreateChampionshipRequest
	(*ChampionshipResponse)(nil),             // 2: game.ChampionshipResponse
	(*ListChampionshipsRequest)(nil),         // 3: game.ListChampionshipsRequest
	(*ListChampionshipsResponse)(nil),        // 4: game.ListChampionshipsResponse
	(*UpdateChampionshipEndDateRequest)(nil), // 5: game.UpdateChampionshipEndDateRequest
	(*DeleteChampionshipRequest)(nil),        // 6: game.DeleteChampionshipRequest
	(*DeleteChampionshipResponse)(nil),       // 7: game.DeleteChampionshipResponse
	(*timestamppb.Timestamp)(nil),            // 8: google.protobuf.Timestamp
}
var file_proto_championship_proto_depIdxs = []int32{
	8,  // 0: game.Championship.start_at:type_name -> google.protobuf.Timestamp
	8,  // 1: game.Championship.end_at:type_name -> google.protobuf.Timestamp
	8,  // 2: game.CreateChampionshipRequest.start_at:type_name -> google.protobuf.Timestamp
	8,  // 3: game.CreateChampionshipRequest.end_at:type_name -> google.protobuf.Timestamp
	0,  // 4: game.ChampionshipResponse.championship:type_name -> game.Championship
	0,  // 5: game.ListChampionshipsResponse.championships:type_name -> game.Championship
	8,  // 6: game.UpdateChampionshipEndDateRequest.new_end_at:type_name -> google.protobuf.Timestamp
	1,  // 7: game.ChampionshipService.CreateChampionship:input_type -> game.CreateChampionshipRequest
	3,  // 8: game.ChampionshipService.ListChampionships:input_type -> game.ListChampionshipsRequest
	5,  // 9: game.ChampionshipService.UpdateChampionshipEndDate:input_type -> game.UpdateChampionshipEndDateRequest
	6,  // 10: game.ChampionshipService.DeleteChampionship:input_type -> game.DeleteChampionshipRequest
	2,  // 11: game.ChampionshipService.CreateChampionship:output_type -> game.ChampionshipResponse
	4,  // 12: game.ChampionshipService.ListChampionships:output_type -> game.ListChampionshipsResponse
	2,  // 13: game.ChampionshipService.UpdateChampionshipEndDate:output_type -> game.ChampionshipResponse
	7,  // 14: game.ChampionshipService.DeleteChampionship:output_type -> game.DeleteChampionshipResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_championship_proto_init() }
func file_proto_championship_proto_init() {
	if File_proto_championship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_championship_proto_rawDesc), len(file_proto_championship_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_championship_proto_goTypes,
		DependencyIndexes: file_proto_championship_proto_depIdxs,
		MessageInfos:      file_proto_championship_proto_msgTypes,
	}.Build()
	File_proto_championship_proto = out.File
	file_proto_championship_proto_goTypes = nil
	file_proto_championship_proto_depIdxs = nil
}
