// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/championship.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Championship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Championship) Reset() {
	*x = Championship{}
	mi := &file_proto_championship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Championship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Championship) ProtoMessage() {}

func (x *Championship) ProtoReflect() protoreflect.Message {
	mi := &file_proto_championship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Championship.ProtoReflect.Descriptor instead.
func (*Championship) Descriptor() ([]byte, []int) {
	return file_proto_championship_proto_rawDescGZIP(), []int{0}
}

func (x *Championship) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Championship) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Championship) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *Championship) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

type CreateChampionshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChampionshipRequest) Reset() {
	*x = CreateChampionshipRequest{}
	mi := &file_proto_championship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChampionshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChampionshipRequest) ProtoMessage() {}

func (x *CreateChampionshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_championship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChampionshipRequest.ProtoReflect.Descriptor instead.
func (*CreateChampionshipRequest) Descriptor() ([]byte, []int) {
	return file_proto_championship_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChampionshipRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChampionshipRequest) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *CreateChampionshipRequest) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

type ChampionshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Championship  *Championship          `protobuf:"bytes,1,opt,name=championship,proto3" json:"championship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChampionshipResponse) Reset() {
	*x = ChampionshipResponse{}
	mi := &file_proto_championship_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChampionshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChampionshipResponse) ProtoMessage() {}

func (x *ChampionshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_championship_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChampionshipResponse.ProtoReflect.Descriptor instead.
func (*ChampionshipResponse) Descriptor() ([]byte, []int) {
	return file_proto_championship_proto_rawDescGZIP(), []int{2}
}

func (x *ChampionshipResponse) GetChampionship() *Championship {
	if x != nil {
		return x.Championship
	}
	return nil
}

var File_proto_championship_proto protoreflect.FileDescriptor

const file_proto_championship_proto_rawDesc = "" +
	"\n" +
	"\x18proto/championship.proto\x12\x04game\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n" +
	"\fChampionship\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\bstart_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\"\x99\x01\n" +
	"\x19CreateChampionshipRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\bstart_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\"N\n" +
	"\x14ChampionshipResponse\x126\n" +
	"\fchampionship\x18\x01 \x01(\v2\x12.game.ChampionshipR\fchampionship2h\n" +
	"\x13ChampionshipService\x12Q\n" +
	"\x12CreateChampionship\x12\x1f.game.CreateChampionshipRequest\x1a\x1a.game.ChampionshipResponseBCZAgithub.com/PatrickCalorioCarvalho/StrideClash/backend/proto;protob\x06proto3"

var (
	file_proto_championship_proto_rawDescOnce sync.Once
	file_proto_championship_proto_rawDescData []byte
)

func file_proto_championship_proto_rawDescGZIP() []byte {
	file_proto_championship_proto_rawDescOnce.Do(func() {
		file_proto_championship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_championship_proto_rawDesc), len(file_proto_championship_proto_rawDesc)))
	})
	return file_proto_championship_proto_rawDescData
}

var file_proto_championship_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_championship_proto_goTypes = []any{
	(*Championship)(nil),              // 0: game.Championship
	(*CreateChampionshipRequest)(nil), // 1: game.CreateChampionshipRequest
	(*ChampionshipResponse)(nil),      // 2: game.ChampionshipResponse
	(*timestamppb.Timestamp)(nil),     // 3: google.protobuf.Timestamp
}
var file_proto_championship_proto_depIdxs = []int32{
	3, // 0: game.Championship.start_at:type_name -> google.protobuf.Timestamp
	3, // 1: game.Championship.end_at:type_name -> google.protobuf.Timestamp
	3, // 2: game.CreateChampionshipRequest.start_at:type_name -> google.protobuf.Timestamp
	3, // 3: game.CreateChampionshipRequest.end_at:type_name -> google.protobuf.Timestamp
	0, // 4: game.ChampionshipResponse.championship:type_name -> game.Championship
	1, // 5: game.ChampionshipService.CreateChampionship:input_type -> game.CreateChampionshipRequest
	2, // 6: game.ChampionshipService.CreateChampionship:output_type -> game.ChampionshipResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_championship_proto_init() }
func file_proto_championship_proto_init() {
	if File_proto_championship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_championship_proto_rawDesc), len(file_proto_championship_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_championship_proto_goTypes,
		DependencyIndexes: file_proto_championship_proto_depIdxs,
		MessageInfos:      file_proto_championship_proto_msgTypes,
	}.Build()
	File_proto_championship_proto = out.File
	file_proto_championship_proto_goTypes = nil
	file_proto_championship_proto_depIdxs = nil
}
