// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/championship.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChampionshipService_CreateChampionship_FullMethodName        = "/game.ChampionshipService/CreateChampionship"
	ChampionshipService_ListChampionships_FullMethodName         = "/game.ChampionshipService/ListChampionships"
	ChampionshipService_UpdateChampionshipEndDate_FullMethodName = "/game.ChampionshipService/UpdateChampionshipEndDate"
	ChampionshipService_DeleteChampionship_FullMethodName        = "/game.ChampionshipService/DeleteChampionship"
)

// ChampionshipServiceClient is the client API for ChampionshipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChampionshipServiceClient interface {
	CreateChampionship(ctx context.Context, in *CreateChampionshipRequest, opts ...grpc.CallOption) (*ChampionshipResponse, error)
	ListChampionships(ctx context.Context, in *ListChampionshipsRequest, opts ...grpc.CallOption) (*ListChampionshipsResponse, error)
	UpdateChampionshipEndDate(ctx context.Context, in *UpdateChampionshipEndDateRequest, opts ...grpc.CallOption) (*ChampionshipResponse, error)
	DeleteChampionship(ctx context.Context, in *DeleteChampionshipRequest, opts ...grpc.CallOption) (*DeleteChampionshipResponse, error)
}

type championshipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChampionshipServiceClient(cc grpc.ClientConnInterface) ChampionshipServiceClient {
	return &championshipServiceClient{cc}
}

func (c *championshipServiceClient) CreateChampionship(ctx context.Context, in *CreateChampionshipRequest, opts ...grpc.CallOption) (*ChampionshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChampionshipResponse)
	err := c.cc.Invoke(ctx, ChampionshipService_CreateChampionship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *championshipServiceClient) ListChampionships(ctx context.Context, in *ListChampionshipsRequest, opts ...grpc.CallOption) (*ListChampionshipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChampionshipsResponse)
	err := c.cc.Invoke(ctx, ChampionshipService_ListChampionships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *championshipServiceClient) UpdateChampionshipEndDate(ctx context.Context, in *UpdateChampionshipEndDateRequest, opts ...grpc.CallOption) (*ChampionshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChampionshipResponse)
	err := c.cc.Invoke(ctx, ChampionshipService_UpdateChampionshipEndDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *championshipServiceClient) DeleteChampionship(ctx context.Context, in *DeleteChampionshipRequest, opts ...grpc.CallOption) (*DeleteChampionshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChampionshipResponse)
	err := c.cc.Invoke(ctx, ChampionshipService_DeleteChampionship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChampionshipServiceServer is the server API for ChampionshipService service.
// All implementations must embed UnimplementedChampionshipServiceServer
// for forward compatibility.
type ChampionshipServiceServer interface {
	CreateChampionship(context.Context, *CreateChampionshipRequest) (*ChampionshipResponse, error)
	ListChampionships(context.Context, *ListChampionshipsRequest) (*ListChampionshipsResponse, error)
	UpdateChampionshipEndDate(context.Context, *UpdateChampionshipEndDateRequest) (*ChampionshipResponse, error)
	DeleteChampionship(context.Context, *DeleteChampionshipRequest) (*DeleteChampionshipResponse, error)
	mustEmbedUnimplementedChampionshipServiceServer()
}

// UnimplementedChampionshipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChampionshipServiceServer struct{}

func (UnimplementedChampionshipServiceServer) CreateChampionship(context.Context, *CreateChampionshipRequest) (*ChampionshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChampionship not implemented")
}
func (UnimplementedChampionshipServiceServer) ListChampionships(context.Context, *ListChampionshipsRequest) (*ListChampionshipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChampionships not implemented")
}
func (UnimplementedChampionshipServiceServer) UpdateChampionshipEndDate(context.Context, *UpdateChampionshipEndDateRequest) (*ChampionshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChampionshipEndDate not implemented")
}
func (UnimplementedChampionshipServiceServer) DeleteChampionship(context.Context, *DeleteChampionshipRequest) (*DeleteChampionshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChampionship not implemented")
}
func (UnimplementedChampionshipServiceServer) mustEmbedUnimplementedChampionshipServiceServer() {}
func (UnimplementedChampionshipServiceServer) testEmbeddedByValue()                             {}

// UnsafeChampionshipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChampionshipServiceServer will
// result in compilation errors.
type UnsafeChampionshipServiceServer interface {
	mustEmbedUnimplementedChampionshipServiceServer()
}

func RegisterChampionshipServiceServer(s grpc.ServiceRegistrar, srv ChampionshipServiceServer) {
	// If the following call panics, it indicates UnimplementedChampionshipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChampionshipService_ServiceDesc, srv)
}

func _ChampionshipService_CreateChampionship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChampionshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChampionshipServiceServer).CreateChampionship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChampionshipService_CreateChampionship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChampionshipServiceServer).CreateChampionship(ctx, req.(*CreateChampionshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChampionshipService_ListChampionships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChampionshipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChampionshipServiceServer).ListChampionships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChampionshipService_ListChampionships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChampionshipServiceServer).ListChampionships(ctx, req.(*ListChampionshipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChampionshipService_UpdateChampionshipEndDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChampionshipEndDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChampionshipServiceServer).UpdateChampionshipEndDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChampionshipService_UpdateChampionshipEndDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChampionshipServiceServer).UpdateChampionshipEndDate(ctx, req.(*UpdateChampionshipEndDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChampionshipService_DeleteChampionship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChampionshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChampionshipServiceServer).DeleteChampionship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChampionshipService_DeleteChampionship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChampionshipServiceServer).DeleteChampionship(ctx, req.(*DeleteChampionshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChampionshipService_ServiceDesc is the grpc.ServiceDesc for ChampionshipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChampionshipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.ChampionshipService",
	HandlerType: (*ChampionshipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChampionship",
			Handler:    _ChampionshipService_CreateChampionship_Handler,
		},
		{
			MethodName: "ListChampionships",
			Handler:    _ChampionshipService_ListChampionships_Handler,
		},
		{
			MethodName: "UpdateChampionshipEndDate",
			Handler:    _ChampionshipService_UpdateChampionshipEndDate_Handler,
		},
		{
			MethodName: "DeleteChampionship",
			Handler:    _ChampionshipService_DeleteChampionship_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/championship.proto",
}
