// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/walk.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalkService_SyncWalk_FullMethodName     = "/walk.WalkService/SyncWalk"
	WalkService_GetUserStats_FullMethodName = "/walk.WalkService/GetUserStats"
	WalkService_ListMyWalks_FullMethodName  = "/walk.WalkService/ListMyWalks"
	WalkService_DeleteWalk_FullMethodName   = "/walk.WalkService/DeleteWalk"
)

// WalkServiceClient is the client API for WalkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalkServiceClient interface {
	SyncWalk(ctx context.Context, in *SyncWalkRequest, opts ...grpc.CallOption) (*SyncWalkResponse, error)
	GetUserStats(ctx context.Context, in *GetUserStatsRequest, opts ...grpc.CallOption) (*GetUserStatsResponse, error)
	ListMyWalks(ctx context.Context, in *ListMyWalksRequest, opts ...grpc.CallOption) (*ListMyWalksResponse, error)
	DeleteWalk(ctx context.Context, in *DeleteWalkRequest, opts ...grpc.CallOption) (*DeleteWalkResponse, error)
}

type walkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalkServiceClient(cc grpc.ClientConnInterface) WalkServiceClient {
	return &walkServiceClient{cc}
}

func (c *walkServiceClient) SyncWalk(ctx context.Context, in *SyncWalkRequest, opts ...grpc.CallOption) (*SyncWalkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncWalkResponse)
	err := c.cc.Invoke(ctx, WalkService_SyncWalk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walkServiceClient) GetUserStats(ctx context.Context, in *GetUserStatsRequest, opts ...grpc.CallOption) (*GetUserStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserStatsResponse)
	err := c.cc.Invoke(ctx, WalkService_GetUserStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walkServiceClient) ListMyWalks(ctx context.Context, in *ListMyWalksRequest, opts ...grpc.CallOption) (*ListMyWalksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyWalksResponse)
	err := c.cc.Invoke(ctx, WalkService_ListMyWalks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walkServiceClient) DeleteWalk(ctx context.Context, in *DeleteWalkRequest, opts ...grpc.CallOption) (*DeleteWalkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWalkResponse)
	err := c.cc.Invoke(ctx, WalkService_DeleteWalk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalkServiceServer is the server API for WalkService service.
// All implementations must embed UnimplementedWalkServiceServer
// for forward compatibility.
type WalkServiceServer interface {
	SyncWalk(context.Context, *SyncWalkRequest) (*SyncWalkResponse, error)
	GetUserStats(context.Context, *GetUserStatsRequest) (*GetUserStatsResponse, error)
	ListMyWalks(context.Context, *ListMyWalksRequest) (*ListMyWalksResponse, error)
	DeleteWalk(context.Context, *DeleteWalkRequest) (*DeleteWalkResponse, error)
	mustEmbedUnimplementedWalkServiceServer()
}

// UnimplementedWalkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalkServiceServer struct{}

func (UnimplementedWalkServiceServer) SyncWalk(context.Context, *SyncWalkRequest) (*SyncWalkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncWalk not implemented")
}
func (UnimplementedWalkServiceServer) GetUserStats(context.Context, *GetUserStatsRequest) (*GetUserStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserStats not implemented")
}
func (UnimplementedWalkServiceServer) ListMyWalks(context.Context, *ListMyWalksRequest) (*ListMyWalksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyWalks not implemented")
}
func (UnimplementedWalkServiceServer) DeleteWalk(context.Context, *DeleteWalkRequest) (*DeleteWalkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWalk not implemented")
}
func (UnimplementedWalkServiceServer) mustEmbedUnimplementedWalkServiceServer() {}
func (UnimplementedWalkServiceServer) testEmbeddedByValue()                     {}

// UnsafeWalkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalkServiceServer will
// result in compilation errors.
type UnsafeWalkServiceServer interface {
	mustEmbedUnimplementedWalkServiceServer()
}

func RegisterWalkServiceServer(s grpc.ServiceRegistrar, srv WalkServiceServer) {
	// If the following call panics, it indicates UnimplementedWalkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalkService_ServiceDesc, srv)
}

func _WalkService_SyncWalk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncWalkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalkServiceServer).SyncWalk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalkService_SyncWalk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalkServiceServer).SyncWalk(ctx, req.(*SyncWalkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalkService_GetUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalkServiceServer).GetUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalkService_GetUserStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalkServiceServer).GetUserStats(ctx, req.(*GetUserStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalkService_ListMyWalks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyWalksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalkServiceServer).ListMyWalks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalkService_ListMyWalks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalkServiceServer).ListMyWalks(ctx, req.(*ListMyWalksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalkService_DeleteWalk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWalkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalkServiceServer).DeleteWalk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalkService_DeleteWalk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalkServiceServer).DeleteWalk(ctx, req.(*DeleteWalkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalkService_ServiceDesc is the grpc.ServiceDesc for WalkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "walk.WalkService",
	HandlerType: (*WalkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncWalk",
			Handler:    _WalkService_SyncWalk_Handler,
		},
		{
			MethodName: "GetUserStats",
			Handler:    _WalkService_GetUserStats_Handler,
		},
		{
			MethodName: "ListMyWalks",
			Handler:    _WalkService_ListMyWalks_Handler,
		},
		{
			MethodName: "DeleteWalk",
			Handler:    _WalkService_DeleteWalk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/walk.proto",
}
