// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/walk.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalkService_StartWalk_FullMethodName  = "/walk.WalkService/StartWalk"
	WalkService_FinishWalk_FullMethodName = "/walk.WalkService/FinishWalk"
)

// WalkServiceClient is the client API for WalkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalkServiceClient interface {
	StartWalk(ctx context.Context, in *StartWalkRequest, opts ...grpc.CallOption) (*StartWalkResponse, error)
	FinishWalk(ctx context.Context, in *FinishWalkRequest, opts ...grpc.CallOption) (*FinishWalkResponse, error)
}

type walkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalkServiceClient(cc grpc.ClientConnInterface) WalkServiceClient {
	return &walkServiceClient{cc}
}

func (c *walkServiceClient) StartWalk(ctx context.Context, in *StartWalkRequest, opts ...grpc.CallOption) (*StartWalkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWalkResponse)
	err := c.cc.Invoke(ctx, WalkService_StartWalk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walkServiceClient) FinishWalk(ctx context.Context, in *FinishWalkRequest, opts ...grpc.CallOption) (*FinishWalkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishWalkResponse)
	err := c.cc.Invoke(ctx, WalkService_FinishWalk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalkServiceServer is the server API for WalkService service.
// All implementations must embed UnimplementedWalkServiceServer
// for forward compatibility.
type WalkServiceServer interface {
	StartWalk(context.Context, *StartWalkRequest) (*StartWalkResponse, error)
	FinishWalk(context.Context, *FinishWalkRequest) (*FinishWalkResponse, error)
	mustEmbedUnimplementedWalkServiceServer()
}

// UnimplementedWalkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalkServiceServer struct{}

func (UnimplementedWalkServiceServer) StartWalk(context.Context, *StartWalkRequest) (*StartWalkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWalk not implemented")
}
func (UnimplementedWalkServiceServer) FinishWalk(context.Context, *FinishWalkRequest) (*FinishWalkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishWalk not implemented")
}
func (UnimplementedWalkServiceServer) mustEmbedUnimplementedWalkServiceServer() {}
func (UnimplementedWalkServiceServer) testEmbeddedByValue()                     {}

// UnsafeWalkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalkServiceServer will
// result in compilation errors.
type UnsafeWalkServiceServer interface {
	mustEmbedUnimplementedWalkServiceServer()
}

func RegisterWalkServiceServer(s grpc.ServiceRegistrar, srv WalkServiceServer) {
	// If the following call panics, it indicates UnimplementedWalkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalkService_ServiceDesc, srv)
}

func _WalkService_StartWalk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWalkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalkServiceServer).StartWalk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalkService_StartWalk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalkServiceServer).StartWalk(ctx, req.(*StartWalkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalkService_FinishWalk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishWalkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalkServiceServer).FinishWalk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalkService_FinishWalk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalkServiceServer).FinishWalk(ctx, req.(*FinishWalkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalkService_ServiceDesc is the grpc.ServiceDesc for WalkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "walk.WalkService",
	HandlerType: (*WalkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartWalk",
			Handler:    _WalkService_StartWalk_Handler,
		},
		{
			MethodName: "FinishWalk",
			Handler:    _WalkService_FinishWalk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/walk.proto",
}
