// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/walk.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncWalk uploads a walk recorded entirely offline: the client generates
// its own id and keeps the walk (and every GPS point) locally the whole
// time, then calls this once network is available. Safe to retry —
// syncing the same client_walk_id twice just replays the same result.
type SyncWalkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientWalkId   string                 `protobuf:"bytes,1,opt,name=client_walk_id,json=clientWalkId,proto3" json:"client_walk_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChampionshipId string                 `protobuf:"bytes,3,opt,name=championship_id,json=championshipId,proto3" json:"championship_id,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Points         []*WalkPoint           `protobuf:"bytes,6,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncWalkRequest) Reset() {
	*x = SyncWalkRequest{}
	mi := &file_proto_walk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWalkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWalkRequest) ProtoMessage() {}

func (x *SyncWalkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_walk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWalkRequest.ProtoReflect.Descriptor instead.
func (*SyncWalkRequest) Descriptor() ([]byte, []int) {
	return file_proto_walk_proto_rawDescGZIP(), []int{0}
}

func (x *SyncWalkRequest) GetClientWalkId() string {
	if x != nil {
		return x.ClientWalkId
	}
	return ""
}

func (x *SyncWalkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncWalkRequest) GetChampionshipId() string {
	if x != nil {
		return x.ChampionshipId
	}
	return ""
}

func (x *SyncWalkRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SyncWalkRequest) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *SyncWalkRequest) GetPoints() []*WalkPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type SyncWalkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolygonWkt    string                 `protobuf:"bytes,1,opt,name=polygon_wkt,json=polygonWkt,proto3" json:"polygon_wkt,omitempty"`
	AreaM2        float64                `protobuf:"fixed64,2,opt,name=area_m2,json=areaM2,proto3" json:"area_m2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncWalkResponse) Reset() {
	*x = SyncWalkResponse{}
	mi := &file_proto_walk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWalkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWalkResponse) ProtoMessage() {}

func (x *SyncWalkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_walk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWalkResponse.ProtoReflect.Descriptor instead.
func (*SyncWalkResponse) Descriptor() ([]byte, []int) {
	return file_proto_walk_proto_rawDescGZIP(), []int{1}
}

func (x *SyncWalkResponse) GetPolygonWkt() string {
	if x != nil {
		return x.PolygonWkt
	}
	return ""
}

func (x *SyncWalkResponse) GetAreaM2() float64 {
	if x != nil {
		return x.AreaM2
	}
	return 0
}

type WalkPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Speed         float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalkPoint) Reset() {
	*x = WalkPoint{}
	mi := &file_proto_walk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkPoint) ProtoMessage() {}

func (x *WalkPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_walk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkPoint.ProtoReflect.Descriptor instead.
func (*WalkPoint) Descriptor() ([]byte, []int) {
	return file_proto_walk_proto_rawDescGZIP(), []int{2}
}

func (x *WalkPoint) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *WalkPoint) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *WalkPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WalkPoint) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type GetUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	mi := &file_proto_walk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_walk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_walk_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalAreaM2   float64                `protobuf:"fixed64,1,opt,name=total_area_m2,json=totalAreaM2,proto3" json:"total_area_m2,omitempty"`
	WalkCount     int32                  `protobuf:"varint,2,opt,name=walk_count,json=walkCount,proto3" json:"walk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsResponse) Reset() {
	*x = GetUserStatsResponse{}
	mi := &file_proto_walk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsResponse) ProtoMessage() {}

func (x *GetUserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_walk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsResponse.ProtoReflect.Descriptor instead.
func (*GetUserStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_walk_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserStatsResponse) GetTotalAreaM2() float64 {
	if x != nil {
		return x.TotalAreaM2
	}
	return 0
}

func (x *GetUserStatsResponse) GetWalkCount() int32 {
	if x != nil {
		return x.WalkCount
	}
	return 0
}

var File_proto_walk_proto protoreflect.FileDescriptor

const file_proto_walk_proto_rawDesc = "" +
	"\n" +
	"\x10proto/walk.proto\x12\x04walk\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x02\n" +
	"\x0fSyncWalkRequest\x12$\n" +
	"\x0eclient_walk_id\x18\x01 \x01(\tR\fclientWalkId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0fchampionship_id\x18\x03 \x01(\tR\x0echampionshipId\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12'\n" +
	"\x06points\x18\x06 \x03(\v2\x0f.walk.WalkPointR\x06points\"L\n" +
	"\x10SyncWalkResponse\x12\x1f\n" +
	"\vpolygon_wkt\x18\x01 \x01(\tR\n" +
	"polygonWkt\x12\x17\n" +
	"\aarea_m2\x18\x02 \x01(\x01R\x06areaM2\"\x7f\n" +
	"\tWalkPoint\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\".\n" +
	"\x13GetUserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Y\n" +
	"\x14GetUserStatsResponse\x12\"\n" +
	"\rtotal_area_m2\x18\x01 \x01(\x01R\vtotalAreaM2\x12\x1d\n" +
	"\n" +
	"walk_count\x18\x02 \x01(\x05R\twalkCount2\x8f\x01\n" +
	"\vWalkService\x129\n" +
	"\bSyncWalk\x12\x15.walk.SyncWalkRequest\x1a\x16.walk.SyncWalkResponse\x12E\n" +
	"\fGetUserStats\x12\x19.walk.GetUserStatsRequest\x1a\x1a.walk.GetUserStatsResponseB@Z>github.com/PatrickCalorioCarvalho/StrideClash/backend/proto;pbb\x06proto3"

var (
	file_proto_walk_proto_rawDescOnce sync.Once
	file_proto_walk_proto_rawDescData []byte
)

func file_proto_walk_proto_rawDescGZIP() []byte {
	file_proto_walk_proto_rawDescOnce.Do(func() {
		file_proto_walk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_walk_proto_rawDesc), len(file_proto_walk_proto_rawDesc)))
	})
	return file_proto_walk_proto_rawDescData
}

var file_proto_walk_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_walk_proto_goTypes = []any{
	(*SyncWalkRequest)(nil),       // 0: walk.SyncWalkRequest
	(*SyncWalkResponse)(nil),      // 1: walk.SyncWalkResponse
	(*WalkPoint)(nil),             // 2: walk.WalkPoint
	(*GetUserStatsRequest)(nil),   // 3: walk.GetUserStatsRequest
	(*GetUserStatsResponse)(nil),  // 4: walk.GetUserStatsResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_walk_proto_depIdxs = []int32{
	5, // 0: walk.SyncWalkRequest.started_at:type_name -> google.protobuf.Timestamp
	5, // 1: walk.SyncWalkRequest.finished_at:type_name -> google.protobuf.Timestamp
	2, // 2: walk.SyncWalkRequest.points:type_name -> walk.WalkPoint
	5, // 3: walk.WalkPoint.timestamp:type_name -> google.protobuf.Timestamp
	0, // 4: walk.WalkService.SyncWalk:input_type -> walk.SyncWalkRequest
	3, // 5: walk.WalkService.GetUserStats:input_type -> walk.GetUserStatsRequest
	1, // 6: walk.WalkService.SyncWalk:output_type -> walk.SyncWalkResponse
	4, // 7: walk.WalkService.GetUserStats:output_type -> walk.GetUserStatsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_walk_proto_init() }
func file_proto_walk_proto_init() {
	if File_proto_walk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_walk_proto_rawDesc), len(file_proto_walk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_walk_proto_goTypes,
		DependencyIndexes: file_proto_walk_proto_depIdxs,
		MessageInfos:      file_proto_walk_proto_msgTypes,
	}.Build()
	File_proto_walk_proto = out.File
	file_proto_walk_proto_goTypes = nil
	file_proto_walk_proto_depIdxs = nil
}
