// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/walk.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartWalkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChampionshipId string                 `protobuf:"bytes,2,opt,name=championship_id,json=championshipId,proto3" json:"championship_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartWalkRequest) Reset() {
	*x = StartWalkRequest{}
	mi := &file_proto_walk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWalkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWalkRequest) ProtoMessage() {}

func (x *StartWalkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_walk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWalkRequest.ProtoReflect.Descriptor instead.
func (*StartWalkRequest) Descriptor() ([]byte, []int) {
	return file_proto_walk_proto_rawDescGZIP(), []int{0}
}

func (x *StartWalkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartWalkRequest) GetChampionshipId() string {
	if x != nil {
		return x.ChampionshipId
	}
	return ""
}

type StartWalkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalkId        string                 `protobuf:"bytes,1,opt,name=walk_id,json=walkId,proto3" json:"walk_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWalkResponse) Reset() {
	*x = StartWalkResponse{}
	mi := &file_proto_walk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWalkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWalkResponse) ProtoMessage() {}

func (x *StartWalkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_walk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWalkResponse.ProtoReflect.Descriptor instead.
func (*StartWalkResponse) Descriptor() ([]byte, []int) {
	return file_proto_walk_proto_rawDescGZIP(), []int{1}
}

func (x *StartWalkResponse) GetWalkId() string {
	if x != nil {
		return x.WalkId
	}
	return ""
}

func (x *StartWalkResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type FinishWalkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalkId        string                 `protobuf:"bytes,1,opt,name=walk_id,json=walkId,proto3" json:"walk_id,omitempty"`
	Points        []*WalkPoint           `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishWalkRequest) Reset() {
	*x = FinishWalkRequest{}
	mi := &file_proto_walk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishWalkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishWalkRequest) ProtoMessage() {}

func (x *FinishWalkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_walk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishWalkRequest.ProtoReflect.Descriptor instead.
func (*FinishWalkRequest) Descriptor() ([]byte, []int) {
	return file_proto_walk_proto_rawDescGZIP(), []int{2}
}

func (x *FinishWalkRequest) GetWalkId() string {
	if x != nil {
		return x.WalkId
	}
	return ""
}

func (x *FinishWalkRequest) GetPoints() []*WalkPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type FinishWalkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolygonWkt    string                 `protobuf:"bytes,1,opt,name=polygon_wkt,json=polygonWkt,proto3" json:"polygon_wkt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishWalkResponse) Reset() {
	*x = FinishWalkResponse{}
	mi := &file_proto_walk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishWalkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishWalkResponse) ProtoMessage() {}

func (x *FinishWalkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_walk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishWalkResponse.ProtoReflect.Descriptor instead.
func (*FinishWalkResponse) Descriptor() ([]byte, []int) {
	return file_proto_walk_proto_rawDescGZIP(), []int{3}
}

func (x *FinishWalkResponse) GetPolygonWkt() string {
	if x != nil {
		return x.PolygonWkt
	}
	return ""
}

type WalkPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalkPoint) Reset() {
	*x = WalkPoint{}
	mi := &file_proto_walk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkPoint) ProtoMessage() {}

func (x *WalkPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_walk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkPoint.ProtoReflect.Descriptor instead.
func (*WalkPoint) Descriptor() ([]byte, []int) {
	return file_proto_walk_proto_rawDescGZIP(), []int{4}
}

func (x *WalkPoint) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *WalkPoint) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *WalkPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_walk_proto protoreflect.FileDescriptor

const file_proto_walk_proto_rawDesc = "" +
	"\n" +
	"\x10proto/walk.proto\x12\x04walk\x1a\x1fgoogle/protobuf/timestamp.proto\"T\n" +
	"\x10StartWalkRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fchampionship_id\x18\x02 \x01(\tR\x0echampionshipId\"g\n" +
	"\x11StartWalkResponse\x12\x17\n" +
	"\awalk_id\x18\x01 \x01(\tR\x06walkId\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"U\n" +
	"\x11FinishWalkRequest\x12\x17\n" +
	"\awalk_id\x18\x01 \x01(\tR\x06walkId\x12'\n" +
	"\x06points\x18\x02 \x03(\v2\x0f.walk.WalkPointR\x06points\"5\n" +
	"\x12FinishWalkResponse\x12\x1f\n" +
	"\vpolygon_wkt\x18\x01 \x01(\tR\n" +
	"polygonWkt\"i\n" +
	"\tWalkPoint\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\x8c\x01\n" +
	"\vWalkService\x12<\n" +
	"\tStartWalk\x12\x16.walk.StartWalkRequest\x1a\x17.walk.StartWalkResponse\x12?\n" +
	"\n" +
	"FinishWalk\x12\x17.walk.FinishWalkRequest\x1a\x18.walk.FinishWalkResponseB@Z>github.com/PatrickCalorioCarvalho/StrideClash/backend/proto;pbb\x06proto3"

var (
	file_proto_walk_proto_rawDescOnce sync.Once
	file_proto_walk_proto_rawDescData []byte
)

func file_proto_walk_proto_rawDescGZIP() []byte {
	file_proto_walk_proto_rawDescOnce.Do(func() {
		file_proto_walk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_walk_proto_rawDesc), len(file_proto_walk_proto_rawDesc)))
	})
	return file_proto_walk_proto_rawDescData
}

var file_proto_walk_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_walk_proto_goTypes = []any{
	(*StartWalkRequest)(nil),      // 0: walk.StartWalkRequest
	(*StartWalkResponse)(nil),     // 1: walk.StartWalkResponse
	(*FinishWalkRequest)(nil),     // 2: walk.FinishWalkRequest
	(*FinishWalkResponse)(nil),    // 3: walk.FinishWalkResponse
	(*WalkPoint)(nil),             // 4: walk.WalkPoint
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_walk_proto_depIdxs = []int32{
	5, // 0: walk.StartWalkResponse.started_at:type_name -> google.protobuf.Timestamp
	4, // 1: walk.FinishWalkRequest.points:type_name -> walk.WalkPoint
	5, // 2: walk.WalkPoint.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: walk.WalkService.StartWalk:input_type -> walk.StartWalkRequest
	2, // 4: walk.WalkService.FinishWalk:input_type -> walk.FinishWalkRequest
	1, // 5: walk.WalkService.StartWalk:output_type -> walk.StartWalkResponse
	3, // 6: walk.WalkService.FinishWalk:output_type -> walk.FinishWalkResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_walk_proto_init() }
func file_proto_walk_proto_init() {
	if File_proto_walk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_walk_proto_rawDesc), len(file_proto_walk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_walk_proto_goTypes,
		DependencyIndexes: file_proto_walk_proto_depIdxs,
		MessageInfos:      file_proto_walk_proto_msgTypes,
	}.Build()
	File_proto_walk_proto = out.File
	file_proto_walk_proto_goTypes = nil
	file_proto_walk_proto_depIdxs = nil
}
